spring.application.name=taskManagerService
server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Dedpsaf56!
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_service

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.check-template-location=false

jwt.secret=S08ZhyUU3kOW6EiO6NlyzHkw-0VgQ_yv-VotnstKNmM
jwt.lifetime=30m

spring.kafka.bootstrap-servers=localhost:9092

scheduler.cron = 0 0/1 * * * *
scheduler.batch-size = 10

jwt.token = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1VTRVIiXSwic3ViIjoibDR6eXIxY2giLCJpYXQiOjE3NDQ3MjA4MDAsImV4cCI6MTc0NDgwNzIwMH0.GRv7Pqb30vZuawkSqzLs6S9f-25As5EAKGhTMNIJ2R4